### ISSUE TITLE
Exported photos not visible to OneDrive app

### ISSUE THREAD

**Issue by devlie** [arthurhammer/FrameGrabber#4] opened 2020-12-07 06:57 UTC
Any idea why OneDrive app seemingly cannot see and upload the saved photos? I tried exporting both using heic and jpg and neither gets auto uploaded. Not sure if this is FrameGrabber or OneDrive issue yet. Thanks!

**Comment by arthurhammer** [comment] 2020-12-21 16:42
Hey @devlie, thanks for your report! 

Help me understand this issue: You saved the exported frame to your iOS photo library (so it appears in Photos app)? And you have set One Drive to auto upload all your photos but it doesn't for the exported frame? 

I'd assume that's an issue with One Drive itself. However, can you try out one thing for me: Can you disable exporting metadata in Frame Grabber and see if One Drive picks up that image? Thanks!

**Comment by arthurhammer** [comment] 2021-01-04 22:28
Feel free to add any more details about the issue! 

Until then, I'm closing this since I can't reproduce the problem.

**Closed as completed by arthurhammer** 2021-01-04 22:28 UTC
Labels: needs more info

**Comment by devlie** [comment] 2021-01-09 18:51
> I'd assume that's an issue with One Drive itself. However, can you try out one thing for me: Can you disable exporting metadata in Frame Grabber and see if One Drive picks up that image? Thanks!

Good catch. I disabled the metadata export, and OneDrive picks up the image fine. Would this be a framegrabber or OneDrive issue then? Thanks!

**Comment by arthurhammer** [comment] 2021-01-20 08:23
My guess is OneDrive doesn't pick up older images, i.e. images imported into your photo library today but taken in the past.

If you enable exporting metadata in Frame Grabber, the creation date metadata tag is exported in the images which could be in the past. If you disable exporting metadata, images get the creation date of now.

However, this is just a guess. I can't verify this because I don't have a OneDrive account. What you could try is import a random pic from the internet and check if OneDrive picks it up. Just make sure it was taken in the past, i.e. its creation date metadata tag is in the past. 

Please report back with the results! :)

In either case, I don't think this is an issue on our end. If the cause is indeed the metadata creation date, then it is an issue on OneDrive's side, i.e. how they decide to sync images.
